### PR TITLE
3 check for clean git

### PR DESCRIPTION
**Pull request by duluca**
fixing vsix

### CODE REVIEW

**Comment by duluca** [comment]
@alexhoffman617 @brendoncaulkins @kentonbmax I got it super close to publishing, but having trouble with `command 'ng-evergreen.angularEvergreen' not found` error after packaging the extension. You can run `npm run package` to create the vsix file and then ctrl+shift+p to install from vsix and try to use it, you'll see the error message. I followed this guide (https://code.visualstudio.com/api/working-with-extensions/bundling-extension) to apply the webpack configuration, tried a whole bunch of things, but couldn't resolve the issue. Help would be most appreciated.

**Comment by duluca** [comment]
This might be it, not infront of laptop until later afternoon. https://stackoverflow.com/a/54797507

**Comment by kentonbmax** [comment]
@duluca your refactor looks good!

**Comment by brendoncaulkins** [comment]
`latest-version` had a dependency on `package-json` which used `got`.  `got` doesn't use webpack safe imports, which caused webpack complaints, and thus `got` was added to the webpack externals list.  This list is effectively peerDependencies, but VSCode doesn't handle those.

Long story short, the app was crashing on load, but VSCode was registering the commands listed in the `package.json` file.

The commit I added removes `latest-version` and swaps in `get-latest-version` which does the exact same thing, but with different dependencies that seem to be webpack safe.

I'm able to successfully install from VSIX and run the extension.

**Comment by brendoncaulkins** [comment]
Also, bumped version to 0.5.2.

**Pull request merged**
