### PR TITLE
24

### PR DESCRIPTION
**Pull request by kentonbmax**
- Need someone to test clean update with 'run' option for me. I don't have an easy project to update currently.

### CODE REVIEW

**Comment by kentonbmax** [comment]
@duluca terminal now has cleaner stdout and you guessed it green text :)

**Comment by duluca** [comment]
@kentonbmax Runs `ng version` but not an actual update

**Comment by duluca** [comment]
Used local-weather-app to test

**Comment by duluca** [comment]
image

**Comment by duluca** [comment]
@kentonbmax fixed portions of the code and moved `updateNg` implementation over to  #28. `execa` is the better way to go about this.

**Pull request closed without merging**
